### ISSUE TITLE
Large collection of jobs throw an exception

### ISSUE THREAD

**Issue by seivan** [joakimk/toniq#32]
```
[error] Process #PID<0.8253.0> raised an exception
** (Protocol.UndefinedError) protocol String.Chars not implemented for {:noproc, {:gen_server, :call, [#PID<0.30669.0>, :stop]}}
    (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir) lib/string/chars.ex:17: String.Chars.to_string/1
    (toniq) lib/toniq/job_process.ex:40: Toniq.JobProcess.wait_for_result/0
    (toniq) lib/toniq/job_process.ex:3: Toniq.JobProcess.run/1
    (toniq) lib/toniq/job_concurrency_limiter.ex:26: Toniq.JobConcurrencyLimiter.run/2
    (toniq) lib/toniq/job_runner.ex:17: anonymous fn/1 in Toniq.JobRunner.handle_cast/2
```

My guess is https://github.com/joakimk/toniq/blob/813f0eca9fa2cda1324979d18643643f3dbfc718/lib/toniq/job_process.ex#L40

Trying to convert `{:noproc, {:gen_server, :call, [#PID<0.30669.0>, :stop]}}` into a `string`
But chances are I'm wrong.

**Comment by gen1321** [comment]
I have almost same issue
```
(Protocol.UndefinedError) protocol String.Chars not implemented for {:connection_error, {:connection_error, :emfile}}
```
